services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=meubanco
    ports:
      - "5432:5432"
    networks: 
      - postgres-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks: 
      - postgres-network
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  produtos-service:
    build: produtos-service
    ports:
      - "8080:8080"  # padrão, sobrescrito se necessário
    networks:
      - ecommerce-network
    volumes:
      - produtos-service:/app  # em produção pode ser removido

  categorias-service:
    build: categorias-service
    ports:
      - "8081:8081"  # padrão, sobrescrito se necessário
    networks:
      - ecommerce-network
    volumes:
      - categorias-service:/app  # em produção pode ser removido

  fornecedores-service:
    build: fornecedores-service
    ports:
      - "8082:8082"  # padrão, sobrescrito se necessário
    networks:
      - ecommerce-network
    volumes:
      - fornecedores-service:/app  # em produção pode ser removido

  avaliacoes-service:
    build: avaliacoes-service
    ports:
      - "8083:8083"  # padrão, sobrescrito se necessário
    networks:
      - ecommerce-network
    volumes:
      - avaliacoes-service:/app  # em produção pode ser removido

networks:
  ecommerce-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

  postgres-network: 
    driver: bridge

volumes:
  produtos-service:
  categorias-service:
  fornecedores-service:
  avaliacoes-service:
  pgdata:
  pgadmin_data:
  phpmyadmin_data:
  db_data: