services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=ecommerce_prod
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"  # exposto ou não, dependendo da infra
    volumes:
      - db_data:/var/lib/mysql

  avaliacoes-service:
    image: tfk8scloud/avaliacoes-ecommerce:latest # imagem versionada e testada
    environment:
      - APP_ENV=prod
      - FLASK_ENV=prod  # não ativa modo debug no Flask
    ports:
      - "8080:8080"

  categorias-service:
    image: tfk8scloud/categorias-ecommerce:latest  # imagem versionada e testada
    environment:
      - APP_ENV=prod
      - FLASK_ENV=prod  # não ativa modo debug no Flask
    ports:
      - "8081:8081"

  fornecedores-service:
    image: tfk8scloud/fornecedores-ecommerce:latest  # imagem versionada e testada
    environment:
      - APP_ENV=prod
      - FLASK_ENV=prod  # não ativa modo debug no Flask
    ports:
      - "8082:8082"

  produtos-service:
    image: tfk8scloud/produtos-ecommerce:latest  # imagem versionada e testada
    environment:
      - APP_ENV=prod
      - FLASK_ENV=prod  # não ativa modo debug no Flask
    ports:
      - "8083:8083"

volumes:
  db_data:
